var store = {
    answers: [{
        index: 1,
        value: ""
    }, {
        index: 2,
        value: ""
    }, {
        index: 3,
        value: ""
    }, {
        index: 4,
        value: ""
    }, {
        index: 5,
        value: ""
    }, {
        index: 6,
        value: ""
    }, {
        index: 7,
        value: ""
    }, {
        index: 8,
        value: ""
    }],
    heroes: [
        {
            image: 1,
            index: 1,
            position: 310
        }, {
            image: 2,
            position: 420
        }, {
            image: 3,
            index: 2,
            position: 635
        }, {
            image: 4,
            position: 1650
        }, {
            image: 5,
            index: 3,
            position: 1800
        }, {
            image: 6,
            position: 1950
        }, {
            image: 7,
            position: 2850
        }, {
            image: 8,
            position: 2950
        }, {
            image: 9,
            index: 4,
            position: 3110
        }, {
            image: 10,
            index: 5,
            position: 3700
        }, {
            image: 11,
            position: 4150
        }, {
            image: 12,
            position: 4900
        }, {
            image: 13,
            index: 6,
            position: 6050
        }, {
            image: 14,
            position: 6600
        }, {
            image: 15,
            index: 7,
            position: 7350
        }, {
            image: 16,
            position: 7500
        }, {
            image: 17,
            index: 8,
            position: 7900
        }
    ],
    tasks: [],
    user: {
        deadline: '2018-11-20 23:59:59',
        firstName: 'Krisztián',
        teamName: 'teamName'
    }
}